import type { FieldPolicyCategory } from './types'

/**
 * Keyword aliases per policy category. Checked in FIELD_POLICY_PRECEDENCE
 * order — never_auto always wins, and anything unmatched falls back to
 * manual_review (conservative default).
 */
export const FIELD_POLICY_PRECEDENCE: readonly FieldPolicyCategory[] = [
  'never_auto',
  'demographic_exact_match_only',
  'manual_review',
  'auto_if_confirmed',
  'safe_auto_fill',
]

export const FIELD_ALIASES: Record<FieldPolicyCategory, readonly string[]> = {
  never_auto: [
    'password',
    'confirm password',
    'otp',
    'one-time password',
    'one time password',
    'verification code',
    'captcha',
    'i am not a robot',
    'accept terms',
    'terms and conditions',
    'terms of use',
    'i agree',
    'certify',
    'declaration of truth',
    'information is true',
    'final submit',
    'submit application',
    'electronic signature',
    'e-signature',
    'sign here',
  ],
  demographic_exact_match_only: [
    'gender',
    'sex',
    'race',
    'ethnicity',
    'ethnic',
    'disability',
    'disabled',
    'veteran',
    'military service',
    'sexual orientation',
    'lgbt',
    'nationality',
    'religion',
  ],
  manual_review: [
    'salary',
    'compensation expectation',
    'expected pay',
    'cover letter',
    'transcript',
    'reference',
    'referee',
    'essay',
    'conflict of interest',
    'background check',
    'regulatory disclosure',
    'criminal',
    'national service',
    'ns status',
  ],
  auto_if_confirmed: [
    'legally authorized',
    'legally authorised',
    'authorized to work',
    'authorised to work',
    'work authorization',
    'work authorisation',
    'right to work',
    'visa sponsorship',
    'require sponsorship',
    'previously applied',
    'applied before',
    'previously employed',
    'previously worked',
    'worked at',
    'relatives',
    'family member',
    'internship availability',
    'available to start',
    'availability',
    'penultimate',
    'graduation year eligibility',
  ],
  safe_auto_fill: [
    'first name',
    'last name',
    'family name',
    'given name',
    'full name',
    'legal name',
    'preferred name',
    'email',
    'e-mail',
    'phone',
    'mobile',
    'contact number',
    'linkedin',
    'address',
    'street',
    'postal code',
    'zip code',
    'city',
    'country of residence',
    'school',
    'university',
    'institution',
    'college',
    'degree',
    'major',
    'field of study',
    'graduation date',
    'expected graduation',
    'gpa',
    'grade point average',
  ],
}
